# Project Title: E-Commerce Sales Performance & Data Integrity Optimization

### <center>Business Problem</center>

The company lacked a reliable way to analyze profitability across its 200,000+ 
multi-region sales records due to data inconsistencies, structural formatting errors, and unverified profit margins, 
which delayed key inventory and pricing decisions.

(A) Messy Raw Data: The company had a massive dataset of over 200,000 sales records, but it was filled with formatting bugs, trailing spaces, and hidden errors.

(B) Broken Reports: These data inconsistencies broke standard reporting tools, making it impossible to run accurate sales or profit metrics.

(C) Blind Decision-Making: Management couldn’t see which regions or product categories were actually making money, leading to a high risk of making bad inventory and pricing decisions.

In [ ]:
# Importing the necessary libraries
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [7]:
# Load 200k raw sales records and strip hidden spaces from column names
df = pd.read_csv("product_sales_dataset_final.csv")
df

,Order_ID,Order_Date,Customer_Name,City,State,Region,Country,Category,Sub_Category,Product_Name,Quantity,Unit_Price,Revenue,Profit
0,1,08-23-23,Bianca Brown,Jackson,Mississippi,South,United States,Accessories,Small Electronics,Phone Case,3,201.01,603.03,221.49
1,2,12-20-24,Jared Edwards,Grand Rapids,Michigan,Centre,United States,Accessories,Small Electronics,Charging Cable,4,74.30,297.20,97.09
2,3,01-29-24,Susan Valdez,Minneapolis,Minnesota,Centre,United States,Clothing & Apparel,Sportswear,Nike Air Force 1,1,68.19,68.19,25.47
3,4,11-29-24,Tina Williams,Tallahassee,Florida,South,United States,Clothing & Apparel,Sportswear,Adidas Tracksuit,3,209.64,628.92,231.38
4,5,09-21-23,Catherine Gordon,Baltimore,Maryland,East,United States,Accessories,Bags,Backpack,1,216.63,216.63,42.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199996,08-15-23,William Jackson,Boston,Massachusetts,East,United States,Home & Furniture,Storage,Storage Rack,4,254.42,1017.68,334.72
199996,199997,10-17-23,Sharon Ferrell,Bismarck,North Dakota,Centre,United States,Accessories,Small Electronics,Charging Cable,1,237.04,237.04,46.53
199997,199998,12-03-23,Katie Rivera,Santa Fe,New Mexico,West,United States,Accessories,Wearable Accessories,Sunglasses,2,106.83,213.66,102.57
199998,199999,12-08-23,Lisa Sullivan,New York City,New York,East,United States,Clothing & Apparel,Women's Wear,Zara Blouse,2,353.01,706.02,288.74
199999,200000,12-13-24,Jessica Mueller,Augusta,Maine,East,United States,Clothing & Apparel,Men's Wear,GAP Hoodie,1,216.68,216.68,59.10

In [20]:
df = pd.read_csv("product_sales_dataset_final.csv")
# # Split into smaller tables (Corrected column names)
orders = df[['Order_ID', 'Order_Date']].drop_duplicates()
customers = df[['Customer_Name', 'City', 'State', 'Region', 'Country']].drop_duplicates()

In [27]:
orders.head(20)

    Order_ID Order_Date
0          1   08-23-23
1          2   12-20-24
2          3   01-29-24
3          4   11-29-24
4          5   09-21-23
5          6   10-18-24
6          7   12-11-24
7          8   05-05-23
8          9   10-25-23
9         10   10-15-23
10        11   06-28-23
11        12   09-09-23
12        13   07-13-23
13        14   10-14-23
14        15   06-21-24
15        16   10-09-23
16        17   08-25-23
17        18   02-25-24
18        19   01-14-23
19        20   03-05-23

In [ ]:
customers.head(20)

         Customer_Name            City          State  Region        Country
0         Bianca Brown         Jackson    Mississippi   South  United States
1        Jared Edwards    Grand Rapids       Michigan  Centre  United States
2         Susan Valdez     Minneapolis      Minnesota  Centre  United States
3        Tina Williams     Tallahassee        Florida   South  United States
4     Catherine Gordon       Baltimore       Maryland    East  United States
5     Brittany Johnson          Boston  Massachusetts    East  United States
6   Katie Rodriguez MD         Seattle     Washington    West  United States
7           John Davis           Tulsa       Oklahoma   South  United States
8         Edward Hicks  Salt Lake City           Utah    West  United States
9    Carrie Cunningham      Fort Smith       Arkansas   South  United States
10      Benjamin Smith       Rochester       New York    East  United States
11      Angela Manning         Augusta          Maine    East  United States
12         Brent Kirby          Boston  Massachusetts    East  United States
13     Tiffany Spencer     Little Rock       Arkansas   South  United States
14       Laura Baldwin          Aurora       Illinois  Centre  United States
15        April Arnold         Atlanta        Georgia   South  United States
16     Jennifer Burton      Montgomery        Alabama   South  United States
17       Kristin Evans        Santa Fe     New Mexico    West  United States
18      Zachary Walker     Baton Rouge      Louisiana   South  United States
19      Amanda Woodard   San Francisco     California    West  United States

In [ ]:
print("Customer Shape:", (customers.shape))

In [ ]:
customers.shape